### ISSUE TITLE
Enable Certificate Request

### ISSUE THREAD

**Issue by huzaifanur** [MuhammadShabaan/hr-portal#4]
I propose the addition of a new feature that would allow users to request certificates from their ex-employers directly through the platform. This feature would streamline the certificate retrieval process, providing a convenient and centralized way for users to obtain necessary documents for employment verification or personal records.

**Comment by MuhammadShabaan** [comment]
We will add this feature in a future release. For now, we are adding this feature for current employees. Your suggestion would be considered if we need to enhance the functionality.
